site_name: L4r1k
site_url: https://l4r1k.github.io/blog/
repo_url: https://github.com/L4r1k/blog/
repo_name: GitHub
site_description: WEB DEVELOPER TURNED CLOUD SECURITY RESEARCHER. THREAT HUNTING/DEVSECOPS/FORENSICS. DRINKER OF DIET COKE. DON'T REPEAT, AUTOMATE.
site_author: L4r1k
remote_branch: gh-pages
remote_name: origin
theme:
  name: material
  palette:
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: deep purple
    accent: deep purple
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
nav:
  - "Blog": "https://l4r1k.com"   
